// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCCUcFPW3Bxdh49a-T5HM7FbbnLBt_OYY',
    appId: '1:1034882966291:web:4e6c7e9ec00c453a8cb0e6',
    messagingSenderId: '1034882966291',
    projectId: 'godoy-resolve-app',
    authDomain: 'godoy-resolve-app.firebaseapp.com',
    storageBucket: 'godoy-resolve-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF6QunV6J00twc48Z2om6P40pRlr6GnE8',
    appId: '1:1034882966291:android:4688c4c5dcbf52948cb0e6',
    messagingSenderId: '1034882966291',
    projectId: 'godoy-resolve-app',
    storageBucket: 'godoy-resolve-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI5ZH4fAuiTOisULnHeXCj2TFRsS7iIrQ',
    appId: '1:1034882966291:ios:1d2cddedacba6dfb8cb0e6',
    messagingSenderId: '1034882966291',
    projectId: 'godoy-resolve-app',
    storageBucket: 'godoy-resolve-app.firebasestorage.app',
    iosBundleId: 'com.sixamtech.demandium.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI5ZH4fAuiTOisULnHeXCj2TFRsS7iIrQ',
    appId: '1:1034882966291:ios:68d5c0c36cc7f0698cb0e6',
    messagingSenderId: '1034882966291',
    projectId: 'godoy-resolve-app',
    storageBucket: 'godoy-resolve-app.firebasestorage.app',
    iosBundleId: 'com.godoyresolve.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCCUcFPW3Bxdh49a-T5HM7FbbnLBt_OYY',
    appId: '1:1034882966291:web:caf3caceea8f4a1e8cb0e6',
    messagingSenderId: '1034882966291',
    projectId: 'godoy-resolve-app',
    authDomain: 'godoy-resolve-app.firebaseapp.com',
    storageBucket: 'godoy-resolve-app.firebasestorage.app',
  );

}